// SPDX-License-Identifier: MIT OR Apache-2.0
// tb_LifNeuron_golden.sv
// Canonical source: spikenaut-core-sv/tb
// Golden-vector testbench for spikenaut-core-sv/rtl/LifNeuron.sv (GH#66).
//
// This is the .mem -> Verilator leg of the f32 -> Q8.8 -> .mem -> Verilator
// path. It does not author any expectation itself: every stimulus and every
// expected value is read from spikenaut-core-sv/mem/golden/, generated by
// scripts/gen_golden_lif_vectors.py from the pinned exp-025 bank. See
// docs/golden-lif-vectors.md.
//
// Complements tb_LifNeuron.sv rather than replacing it: that testbench asserts
// hand-written properties of the signed path, this one replays real bank words
// and fails on any numeric drift from the committed trace.
//
// Stimulus is driven and sampled on negedge clk, matching every other core TB.

`timescale 1ns/1ps

// File paths are module parameters so Vivado's sim_core.tcl can pass absolute
// paths (XSim's CWD is the sim run dir, not the repo root). Defaults are
// repo-root relative for Verilator CI, matching tb_WeightRam_init.sv.
module tb_LifNeuron_golden #(
    parameter string WEIGHT_FILE    = "spikenaut-core-sv/mem/golden/lif_golden_weights.mem",
    parameter string THRESHOLD_FILE = "spikenaut-core-sv/mem/golden/lif_golden_thresholds.mem",
    parameter string LEAK_FILE      = "spikenaut-core-sv/mem/golden/lif_golden_leaks.mem",
    parameter string SPIKE_IN_FILE  = "spikenaut-core-sv/mem/golden/lif_golden_spike_in.mem",
    parameter string RESET_FILE     = "spikenaut-core-sv/mem/golden/lif_golden_reset.mem",
    parameter string EXP_MEM_FILE   = "spikenaut-core-sv/mem/golden/lif_golden_exp_membrane.mem",
    parameter string EXP_SPIKE_FILE = "spikenaut-core-sv/mem/golden/lif_golden_exp_spike.mem",
    parameter string COUNT_FILE     = "spikenaut-core-sv/mem/golden/lif_golden_count.mem"
);

    localparam int DATA_WIDTH  = 16;
    localparam int PARAM_WIDTH = 16;
    localparam int CLK_PERIOD  = 10;
    // Headroom over the committed vector count. The count file is what
    // actually bounds the loop; this only sizes the arrays.
    localparam int MAX_VECTORS = 512;

    logic                   clk;
    logic                   rst_n;
    logic                   step_en;
    logic                   spike_in;
    logic [DATA_WIDTH-1:0]  weight;
    logic [PARAM_WIDTH-1:0] threshold;
    logic [PARAM_WIDTH-1:0] leak;
    logic                   spike_out;

    int errors = 0;
    int n_vectors;

    logic [DATA_WIDTH-1:0]  weight_vec    [0:MAX_VECTORS-1];
    logic [PARAM_WIDTH-1:0] threshold_vec [0:MAX_VECTORS-1];
    logic [PARAM_WIDTH-1:0] leak_vec      [0:MAX_VECTORS-1];
    logic [15:0]            spike_in_vec  [0:MAX_VECTORS-1];
    logic [15:0]            reset_vec     [0:MAX_VECTORS-1];
    logic [DATA_WIDTH-1:0]  exp_mem_vec   [0:MAX_VECTORS-1];
    logic [15:0]            exp_spike_vec [0:MAX_VECTORS-1];
    logic [15:0]            count_vec     [0:0];

    LifNeuron #(
        .DATA_WIDTH  (DATA_WIDTH),
        .PARAM_WIDTH (PARAM_WIDTH)
    ) dut (
        .clk       (clk),
        .rst_n     (rst_n),
        .step_en   (step_en),
        .spike_in  (spike_in),
        .weight    (weight),
        .threshold (threshold),
        .leak      (leak),
        .spike_out (spike_out)
    );

    initial clk = 1'b0;
    always #(CLK_PERIOD/2) clk = ~clk;

    // Fail loudly rather than silently loading nothing: a mistyped or
    // unresolved path would otherwise leave every array X and "pass" by
    // running zero vectors.
    task automatic require_file(input string path);
        int fd;
        fd = $fopen(path, "r");
        if (fd == 0)
            $fatal(1, "TB_LIFNEURON_GOLDEN: cannot open '%s' (run from the repo root, or override the *_FILE parameters)", path);
        $fclose(fd);
    endtask

    initial begin
        require_file(WEIGHT_FILE);
        require_file(THRESHOLD_FILE);
        require_file(LEAK_FILE);
        require_file(SPIKE_IN_FILE);
        require_file(RESET_FILE);
        require_file(EXP_MEM_FILE);
        require_file(EXP_SPIKE_FILE);
        require_file(COUNT_FILE);

        $readmemh(WEIGHT_FILE,    weight_vec);
        $readmemh(THRESHOLD_FILE, threshold_vec);
        $readmemh(LEAK_FILE,      leak_vec);
        $readmemh(SPIKE_IN_FILE,  spike_in_vec);
        $readmemh(RESET_FILE,     reset_vec);
        $readmemh(EXP_MEM_FILE,   exp_mem_vec);
        $readmemh(EXP_SPIKE_FILE, exp_spike_vec);
        $readmemh(COUNT_FILE,     count_vec);

        n_vectors = int'(count_vec[0]);
        if (n_vectors <= 0 || n_vectors > MAX_VECTORS)
            $fatal(1, "TB_LIFNEURON_GOLDEN: vector count %0d is out of range 1..%0d", n_vectors, MAX_VECTORS);

        // Guard against a vacuous pass. If the golden images failed to load
        // (or were truncated to nothing), every expectation would be zero and
        // an idle DUT would "match" all of them. A real vector set always
        // opens a scenario with a reset and reaches a non-zero membrane.
        //
        // Exact per-file length equality is checked by
        // tests/test_golden_lif_vectors.py, which counts lines directly --
        // $readmemh cannot report how many words it loaded, and the usual
        // $isunknown trick does not work here because Verilator
        // zero-initialises array entries it never wrote.
        begin : vacuity_guard
            automatic bit saw_reset = 1'b0;
            automatic bit saw_nonzero_membrane = 1'b0;
            for (int i = 0; i < n_vectors; i++) begin
                if (reset_vec[i][0])    saw_reset = 1'b1;
                if (exp_mem_vec[i] != '0) saw_nonzero_membrane = 1'b1;
            end
            if (!saw_reset || !saw_nonzero_membrane)
                $fatal(1, "TB_LIFNEURON_GOLDEN: golden images look empty or unloaded (reset seen=%b, non-zero membrane seen=%b) -- run from the repo root and regenerate with scripts/gen_golden_lif_vectors.py",
                       saw_reset, saw_nonzero_membrane);
        end

        $display("TB_LIFNEURON_GOLDEN: replaying %0d golden ticks", n_vectors);

        rst_n     = 1'b0;
        step_en   = 1'b0;
        spike_in  = 1'b0;
        weight    = '0;
        threshold = '0;
        leak      = '0;
        @(negedge clk);

        for (int i = 0; i < n_vectors; i++) begin
            // A set reset flag starts a new scenario: one rst_n-asserted clock
            // clears the membrane and the spike_out flop, mirroring the
            // reference model's reset_state().
            if (reset_vec[i][0]) begin
                rst_n = 1'b0;
                @(negedge clk);
                rst_n = 1'b1;
            end

            weight    = weight_vec[i];
            threshold = threshold_vec[i];
            leak      = leak_vec[i];
            spike_in  = spike_in_vec[i][0];
            step_en   = 1'b1;
            @(negedge clk);

            if ($isunknown(dut.membrane_potential) || $isunknown(spike_out)) begin
                errors++;
                $display("FAIL tick %0d: DUT produced X/Z (membrane=%h spike_out=%b)",
                         i, dut.membrane_potential, spike_out);
            end else begin
                if (dut.membrane_potential !== exp_mem_vec[i]) begin
                    errors++;
                    $display("FAIL tick %0d: membrane %h (%0d) != golden %h (%0d)  [w=%h th=%h leak=%h spike_in=%b]",
                             i, dut.membrane_potential, $signed(dut.membrane_potential),
                             exp_mem_vec[i], $signed(exp_mem_vec[i]),
                             weight, threshold, leak, spike_in);
                end
                if (spike_out !== exp_spike_vec[i][0]) begin
                    errors++;
                    $display("FAIL tick %0d: spike_out %b != golden %b  [w=%h th=%h leak=%h spike_in=%b]",
                             i, spike_out, exp_spike_vec[i][0], weight, threshold, leak, spike_in);
                end
            end
        end

        if (errors == 0) begin
            $display("TB_LIFNEURON_GOLDEN: ALL %0d GOLDEN TICKS MATCHED", n_vectors);
            $finish;
        end else begin
            $display("TB_LIFNEURON_GOLDEN: %0d MISMATCH(ES)", errors);
            $display("  Tick indices map to scenarios in spikenaut-core-sv/mem/golden/golden_vectors.json.");
            $display("  If this is an intended LIF semantics change, regenerate the vectors");
            $display("  (python3 scripts/gen_golden_lif_vectors.py) in the same commit as the RTL change.");
            $fatal(1, "TB_LIFNEURON_GOLDEN: testbench FAILED");
        end
    end

endmodule
