// SPDX-License-Identifier: MIT OR Apache-2.0
// tb_OutputLayer_golden.sv
// Canonical source: spikenaut-core-sv/tb
// Golden-vector testbench for spikenaut-core-sv/rtl/OutputLayer.sv (GH#66,
// covering the output-layer hooks GH#72 added).
//
// Same contract as tb_LifNeuron_golden.sv: every expectation comes from
// spikenaut-core-sv/mem/golden/, generated by
// scripts/gen_golden_lif_vectors.py from the pinned exp-025 bank. Nothing is
// asserted from hand-written constants here.
//
// It drives the real WeightRam loaded from the shipped
// merged_v2_output_weights.mem -- the same image the SoC's u_output_wram
// instantiates -- so the .mem -> argmax path under test is the deployed one.
// Neurons 12-15 carry non-positive output weights, so the golden bitmaps that
// select them fail loudly under an unsigned misread of the bank.
//
// Stimulus and checks run on negedge clk, matching every other core TB.

`timescale 1ns/1ps

module tb_OutputLayer_golden #(
    parameter string INIT_FILE   = "spikenaut-core-sv/mem/merged_v2_output_weights.mem",
    parameter string BITMAP_FILE = "spikenaut-core-sv/mem/golden/outlayer_golden_bitmap.mem",
    parameter string RESULT_FILE = "spikenaut-core-sv/mem/golden/outlayer_golden_exp_result.mem",
    parameter string COUNT_FILE  = "spikenaut-core-sv/mem/golden/outlayer_golden_count.mem"
);

    localparam int DATA_WIDTH        = 16;
    localparam int NUM_NEURONS       = 16;
    localparam int NUM_CLASSES       = 3;
    localparam int WEIGHT_ADDR_WIDTH = 6;   // 2**6 = 64 >= 48 entries
    localparam int CLK_PERIOD        = 10;
    localparam int MAX_VECTORS       = 256;
    // The sweep is TOTAL_PAIRS (48) requests plus pipeline fill/drain; 80 is
    // the same bound tb_OutputLayer.sv uses.
    localparam int SWEEP_TIMEOUT     = 80;

    logic                         clk;
    logic                         rst_n;
    logic                         spike_valid;
    logic [NUM_NEURONS-1:0]       spike_bitmap;
    logic [DATA_WIDTH-1:0]        weight_dout;
    logic [WEIGHT_ADDR_WIDTH-1:0] weight_addr;
    logic [NUM_CLASSES-1:0]       result;
    logic                         done;

    int errors = 0;
    int n_vectors;

    logic [15:0] bitmap_vec [0:MAX_VECTORS-1];
    logic [15:0] result_vec [0:MAX_VECTORS-1];
    logic [15:0] count_vec  [0:0];

    WeightRam #(
        .ADDR_WIDTH (WEIGHT_ADDR_WIDTH),
        .DATA_WIDTH (DATA_WIDTH),
        .INIT_FILE  (INIT_FILE)
    ) u_wram (
        .clk   (clk),
        .rst_n (rst_n),
        .we    (1'b0),
        .addr  (weight_addr),
        .din   ('0),
        .dout  (weight_dout)
    );

    OutputLayer #(
        .DATA_WIDTH        (DATA_WIDTH),
        .NUM_NEURONS       (NUM_NEURONS),
        .NUM_CLASSES       (NUM_CLASSES),
        .WEIGHT_ADDR_WIDTH (WEIGHT_ADDR_WIDTH)
    ) dut (
        .clk          (clk),
        .rst_n        (rst_n),
        .spike_valid  (spike_valid),
        .spike_bitmap (spike_bitmap),
        .weight_dout  (weight_dout),
        .weight_addr  (weight_addr),
        .result       (result),
        .done         (done)
    );

    initial clk = 1'b0;
    always #(CLK_PERIOD/2) clk = ~clk;

    task automatic require_file(input string path);
        int fd;
        fd = $fopen(path, "r");
        if (fd == 0)
            $fatal(1, "TB_OUTPUTLAYER_GOLDEN: cannot open '%s' (run from the repo root, or override the *_FILE parameters)", path);
        $fclose(fd);
    endtask

    // Present one bitmap and wait for the sweep to strobe done.
    task automatic run_layer(input logic [NUM_NEURONS-1:0] bitmap, output bit finished);
        int unsigned waited;
        begin
            spike_bitmap = bitmap;
            @(negedge clk);
            spike_valid = 1'b1;
            @(negedge clk);
            spike_valid = 1'b0;
            waited = 0;
            while (done !== 1'b1 && waited < SWEEP_TIMEOUT) begin
                @(negedge clk);
                waited++;
            end
            finished = (done === 1'b1);
        end
    endtask

    initial begin
        bit finished;

        require_file(INIT_FILE);
        require_file(BITMAP_FILE);
        require_file(RESULT_FILE);
        require_file(COUNT_FILE);

        $readmemh(BITMAP_FILE, bitmap_vec);
        $readmemh(RESULT_FILE, result_vec);
        $readmemh(COUNT_FILE,  count_vec);

        n_vectors = int'(count_vec[0]);
        if (n_vectors <= 0 || n_vectors > MAX_VECTORS)
            $fatal(1, "TB_OUTPUTLAYER_GOLDEN: vector count %0d is out of range 1..%0d", n_vectors, MAX_VECTORS);

        // Vacuity guard, same reasoning as tb_LifNeuron_golden.sv: a one-hot
        // result is never zero, so an all-zero expectation array means the
        // golden images did not load. Exact file lengths are checked by
        // tests/test_golden_lif_vectors.py.
        begin : vacuity_guard
            automatic bit saw_result = 1'b0;
            for (int i = 0; i < n_vectors; i++)
                if (result_vec[i] != '0) saw_result = 1'b1;
            if (!saw_result)
                $fatal(1, "TB_OUTPUTLAYER_GOLDEN: golden images look empty or unloaded -- run from the repo root and regenerate with scripts/gen_golden_lif_vectors.py");
        end

        $display("TB_OUTPUTLAYER_GOLDEN: replaying %0d golden bitmaps", n_vectors);

        rst_n        = 1'b0;
        spike_valid  = 1'b0;
        spike_bitmap = '0;
        repeat (2) @(negedge clk);
        rst_n = 1'b1;
        @(negedge clk);

        for (int i = 0; i < n_vectors; i++) begin
            run_layer(bitmap_vec[i][NUM_NEURONS-1:0], finished);

            if (!finished) begin
                errors++;
                $display("FAIL vector %0d (bitmap %04h): sweep did not finish within %0d cycles",
                         i, bitmap_vec[i], SWEEP_TIMEOUT);
            end else if ($isunknown(result)) begin
                errors++;
                $display("FAIL vector %0d (bitmap %04h): result has X/Z (%b)", i, bitmap_vec[i], result);
            end else if (result !== result_vec[i][NUM_CLASSES-1:0]) begin
                errors++;
                $display("FAIL vector %0d (bitmap %04h): result %b != golden %b",
                         i, bitmap_vec[i], result, result_vec[i][NUM_CLASSES-1:0]);
            end
        end

        if (errors == 0) begin
            $display("TB_OUTPUTLAYER_GOLDEN: ALL %0d GOLDEN VECTORS MATCHED", n_vectors);
            $finish;
        end else begin
            $display("TB_OUTPUTLAYER_GOLDEN: %0d MISMATCH(ES)", errors);
            $display("  Vector indices map to entries in spikenaut-core-sv/mem/golden/golden_vectors.json.");
            $display("  If this is an intended output-layer change, regenerate the vectors");
            $display("  (python3 scripts/gen_golden_lif_vectors.py) in the same commit as the RTL change.");
            $fatal(1, "TB_OUTPUTLAYER_GOLDEN: testbench FAILED");
        end
    end

endmodule
